### ISSUE TITLE
Add support for Robot Spline interpolation

### ISSUE THREAD

**Issue by urrsk** [UniversalRobots/Universal_Robots_ROS_Driver#652]
### Feature summery
Improve robustness for spline execution by letting the robot do interpolation

### Related issues
https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/151

### Tasks
- [x] Implement the feature
- [ ] Make documentation
- [x] Make Unit test
- [x] Make example
- [x] Test on real hardware
